### ISSUE TITLE
rasterVis histogram alignment

### ISSUE THREAD

**Issue by dispersing** [Pakillo/GISwithR#1]
First, very nice presentation.  This looks like an incredibly useful tutorial for those looking to use R for GIS data.  (I came across this from Pedro Jordano's retweet.)

Second, it seems like the image `rastervis.png` has two histograms that extend beyond the extent of the spatial data.  I was going to try to look at and help with the code, but I cannot find it here.  

Anyway, just thought I'd let you know and thank you for this.

**Comment by Pakillo** [comment]
Thanks Christopher. Glad you liked it. 

The code (Rmd) used to generate the slides is here: https://github.com/Pakillo/GISwithR/blob/R-AEET-Nov2016/RasGIS.Rmd. Images don't appear as nice here as in R as I had to fiddle their formats a bit so they fit in the slides. 
For the rasterVis levelplot, I think the histograms might appear to stretch further due to a few islets hard to see in the map. Try running the function in your R console... But otherwise it might be a bug in the levelplot function, as I'm just calling it with the elevation raster.

Cheers!

Paco
